version: "3.2"

services:
  nextcloud-db:
    image: postgres
    container_name: nextcloud-db
    restart: always
    volumes:
      - nextcloud-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud-app:/var/www/html
    environment:
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - NEXTCLOUD_ADMIN_PASSWORD
      - NEXTCLOUD_ADMIN_USER
    depends_on:
      - nextcloud-db

volumes:
  nextcloud-db:
  nextcloud-app:
